WingtipToys_MVC/Web/Controllers/CategoriasController.cs
using BaseModels;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Web.Models;

namespace Web.Controllers
{
    public class CategoriasController : Controller
    {
        //contexto do banco de dados
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Categorias
        public ActionResult Index()
        {
            var categorias = db.Categorias.ToList();
            //filtro
            //categorias.Where();
            return View(categorias);
        }
        //GET- CADASTAR NOVA CATEGOIRIA   
        //chamando o carregamento da Pagina View      
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]//MÉTODO POST - cria categoria
        public ActionResult Create(Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                db.Categorias.Add(categoria);
                db.SaveChanges();
                return RedirectToAction("Index");
            }            
                return View(); 
        }

        //Exibição de detalhes do objeto
        //GET
        public ActionResult Details(int? id)
        {
            //não passou id
            if(id == null /*id.Hasvalue*/)
            {
                //errro http 400
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //
            Categoria categoria = db.Categorias.Find(id);
            //não encontrou
            if(categoria == null)
            {
                //
                return HttpNotFound();
            }
            //encontrou id no banco retorna o objeto para view
            return View(categoria);
        }

        //Eidtar categoria
        //GET 
        public ActionResult Edit(int? id)
        {
            //não passou id
            if (id == null /*id.Hasvalue*/)
            {
                //errro http 400
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //
            Categoria categoria = db.Categorias.Find(id);
            //não encontrou
            if (categoria == null)
            {
                //erro http 404
                return HttpNotFound();
            }
            //encontrou id no banco retorna o objeto para view
            return View(categoria);
        }
        //Set editar
         [HttpPost] 
        public ActionResult Edit(Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                db.Entry(categoria).State =
                    System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("index");
            }
            return View(categoria);
        }

        //Excluir
        //Get
        public ActionResult Delete(int? id)
        {
            //não passou id
            if (id == null /*id.Hasvalue*/)
            {
                //erro http 400
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //
            Categoria categoria = db.Categorias.Find(id);
            //não encontrou
            if (categoria == null)
            {
                //
                return HttpNotFound();
            }
            //encontrou id no banco retorna o objeto para view
            return View(categoria);
        }

        //SET
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int? id)
        {
            Categoria categoria = db.Categorias.Find(id);
            db.Categorias.Remove(categoria);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

WingtipToys_MVC/Web/Controllers/ProdutosController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using BaseModels;
using Web.Models;

namespace Web.Controllers
{
    public class ProdutosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Produtos
        public ActionResult Index()
        {
            var produtos = db.Produtos.Include(p => p._Categoria);
            return View(produtos.ToList());
        }

        // GET: Produtos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto produto = db.Produtos.Find(id);
            if (produto == null)
            {
                return HttpNotFound();
            }
            return View(produto);
        }

        // GET: Produtos/Create
        public ActionResult Create()
        {
            ViewBag.CategoriaID = new SelectList(db.Categorias, "CategoriaID", "Nome");
            return View();
        }

        // POST: Produtos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProdutoID,Nome,Descricao,Ativo,CategoriaID")] Produto produto)
        {
            if (ModelState.IsValid)
            {
                db.Produtos.Add(produto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoriaID = new SelectList(db.Categorias, "CategoriaID", "Nome", produto.CategoriaID);
            return View(produto);
        }

        // GET: Produtos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto produto = db.Produtos.Find(id);
            if (produto == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoriaID = new SelectList(db.Categorias, "CategoriaID", "Nome", produto.CategoriaID);
            return View(produto);
        }

        // POST: Produtos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProdutoID,Nome,Descricao,Ativo,CategoriaID")] Produto produto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(produto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoriaID = new SelectList(db.Categorias, "CategoriaID", "Nome", produto.CategoriaID);
            return View(produto);
        }

        // GET: Produtos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto produto = db.Produtos.Find(id);
            if (produto == null)
            {
                return HttpNotFound();
            }
            return View(produto);
        }

        // POST: Produtos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Produto produto = db.Produtos.Find(id);
            db.Produtos.Remove(produto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WingtipToys_MVC/Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>                 
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                     

                    @Html.Partial("_LoginPartial")

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Produto<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Produtos Cadastrados", "Index", "Produtos")</li>
                            <li>@Html.ActionLink("Novo Produto", "Create", "Produtos")</li>

                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categoria<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Categorias Cadastradas", "Index", "Categorias")</li>                           
                            <li>@Html.ActionLink("Nova Categoria", "Create", "Categorias")</li>
                            <li>@Html.ActionLink("Editar", "Edit", "Categorias")</li>
                            <li>@Html.ActionLink("Detalhes", "Details", "Categorias")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>